language: rust
sudo: false
rust:
    - 1.1.0
    - beta
    - nightly
script:
    - cd $TRAVIS_BUILD_DIR/remutex && cargo build --verbose && cargo test --verbose
    - cd $TRAVIS_BUILD_DIR && cargo build --verbose && cargo test --verbose
addons:
    apt:
        packages:
            - libhdf5-serial-dev
            - pkg-config
notifications:
    email: false
os:
    - linux
    - osx
