[package]

name = "hdf5"
version = "0.0.1"
authors = ["Ivan Smirnov <i.s.smirnov@gmail.com>"]
keywords = ["hdf5"]
readme = "README.md"
description = "Thread-safe Rust bindings for the HDF5 library."
repository = "https://github.com/aldanor/hdf5-rs"
homepage = "https://github.com/aldanor/hdf5-rs"

[dependencies]
lazy_static = "*"
num = "*"
libc = "*"

[dependencies.libhdf5-sys]
path = "libhdf5-sys"
version = "0.0.1"

[dependencies.remutex]
path = "remutex"

[dev-dependencies]
regex = "*"
tempdir = "*"
